LOCAL_PATH := device/itel/L6006

PRODUCT_PLATFORM := sp9832e

# API
PRODUCT_SHIPPING_API_LEVEL := 29

# Dynamic Partitions stuff
PRODUCT_USE_DYNAMIC_PARTITIONS := true

# VNDK
PRODUCT_TARGET_VNDK_VERSION := 29

PRODUCT_PROPERTY_OVERRIDES += ro.apex.updatable=false
